# Project Pulse

## Notebook
01 - Data Loading

## Goal
Load the exported YouTube Studio dataset into Python and understand its structure.

## Author
Auhlada Sree Vyshnavi

## Date
30 June 2026

In [151]:
import pandas as pd

# Display all columns during data exploration.
# Pandas hides middle columns with "..." when there are too many columns.
#pd.set_option('display.max_columns', None) 
# Similar option:
#pd.set_option('display.max_rows', None)
# Usually avoided because large datasets become difficult to read.

In [152]:
# Load raw YouTube export into a DataFrame
df = pd.read_csv("../data/raw/table_data.csv")

In [153]:
# Preview the first 5 rows of the dataset.
df.head() 
# Useful alternatives:
# df.tail()     -> last 5 rows
# df.head(10)   -> first 10 rows
# df.tail(10)   -> last 10 rows

,Content,Video title,Video publish time,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average view duration,Average percentage viewed (%),Stayed to watch (%),Unique viewers,Unique reach,Average views per viewer,New viewers,Returning viewers,Casual viewers,Regular viewers,Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
0,Total,NaN,NaN,NaN,679,229,19923,806,96.11,376,137,11.0,6529.0,1187555,0:00:14,105.58,68.13,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0,2613362,5180.1610,450,43552,4.59
1,VE6EZGr29NA,Chikiri 👌 Lyrics💀,"Nov 11, 2025",16.0,562,82,15593,670,95.88,157,69,11.0,6533.0,891614,0:00:15,98.03,67.24,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,1794814,4089.6655,480,10891,6.88
2,H6yMF28ZyQk,IBOMMA RAVI Case Solved!,"Nov 19, 2025",6.0,41,14,2365,82,96.65,13,15,NaN,NaN,155069,0:00:13,219.10,76.05,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,489865,589.3004,27,877,3.88
3,irfyNRSMh88,ME IN 2025,"Dec 3, 2025",12.0,10,0,141,6,95.92,5,0,NaN,NaN,14483,0:00:12,104.64,75.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29662,52.8250,10,476,3.57
4,NA2ZvoTvR6c,"If you can survive this, you can survive anyth...","Dec 22, 2025",8.0,6,0,236,3,98.74,83,5,NaN,NaN,13960,0:00:09,118.19,74.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29639,39.1920,6,443,6.32

In [154]:
# Removed the summary row ('Total') because each row in our ML dataset should represent exactly one YouTube Short.
df = df[df["Content"] != "Total"]
# Preview cleaned DataFrame.
df.head()

,Content,Video title,Video publish time,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average view duration,Average percentage viewed (%),Stayed to watch (%),Unique viewers,Unique reach,Average views per viewer,New viewers,Returning viewers,Casual viewers,Regular viewers,Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
1,VE6EZGr29NA,Chikiri 👌 Lyrics💀,"Nov 11, 2025",16.0,562,82,15593,670,95.88,157,69,11.0,6533.0,891614,0:00:15,98.03,67.24,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,1794814,4089.6655,480,10891,6.88
2,H6yMF28ZyQk,IBOMMA RAVI Case Solved!,"Nov 19, 2025",6.0,41,14,2365,82,96.65,13,15,NaN,NaN,155069,0:00:13,219.10,76.05,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,489865,589.3004,27,877,3.88
3,irfyNRSMh88,ME IN 2025,"Dec 3, 2025",12.0,10,0,141,6,95.92,5,0,NaN,NaN,14483,0:00:12,104.64,75.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29662,52.8250,10,476,3.57
4,NA2ZvoTvR6c,"If you can survive this, you can survive anyth...","Dec 22, 2025",8.0,6,0,236,3,98.74,83,5,NaN,NaN,13960,0:00:09,118.19,74.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29639,39.1920,6,443,6.32
5,38KNroE0RcI,Daddy covering after hurting MOM 😅😂,"Dec 2, 2025",35.0,5,0,55,6,90.16,5,0,NaN,NaN,7420,0:00:24,70.31,57.63,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,15884,53.6322,5,554,1.08

In [155]:
df.shape

(60, 31)

In [156]:
df.columns

Index(['Content', 'Video title', 'Video publish time', 'Duration',
       'Subscribers gained', 'Subscribers lost', 'Likes', 'Dislikes',
       'Likes (vs dislikes) (%)', 'Shares', 'Comments added', 'Remix count',
       'Remix views', 'Engaged views', 'Average view duration',
       'Average percentage viewed (%)', 'Stayed to watch (%)',
       'Unique viewers', 'Unique reach', 'Average views per viewer',
       'New viewers', 'Returning viewers', 'Casual viewers', 'Regular viewers',
       'Hypes', 'Hype points', 'Views', 'Watch time (hours)', 'Subscribers',
       'Impressions', 'Impressions click-through rate (%)'],
      dtype='object')

In [157]:
type(df.columns)

pandas.core.indexes.base.Index

In [158]:
list(df.columns)

['Content',
 'Video title',
 'Video publish time',
 'Duration',
 'Subscribers gained',
 'Subscribers lost',
 'Likes',
 'Dislikes',
 'Likes (vs dislikes) (%)',
 'Shares',
 'Comments added',
 'Remix count',
 'Remix views',
 'Engaged views',
 'Average view duration',
 'Average percentage viewed (%)',
 'Stayed to watch (%)',
 'Unique viewers',
 'Unique reach',
 'Average views per viewer',
 'New viewers',
 'Returning viewers',
 'Casual viewers',
 'Regular viewers',
 'Hypes',
 'Hype points',
 'Views',
 'Watch time (hours)',
 'Subscribers',
 'Impressions',
 'Impressions click-through rate (%)']

In [159]:
df.dtypes

Content                                object
Video title                            object
Video publish time                     object
Duration                              float64
Subscribers gained                      int64
Subscribers lost                        int64
Likes                                   int64
Dislikes                                int64
Likes (vs dislikes) (%)               float64
Shares                                  int64
Comments added                          int64
Remix count                           float64
Remix views                           float64
Engaged views                           int64
Average view duration                  object
Average percentage viewed (%)         float64
Stayed to watch (%)                   float64
Unique viewers                        float64
Unique reach                            int64
Average views per viewer              float64
New viewers                           float64
Returning viewers                     float64
Casual viewers                        float64
Regular viewers                       float64
Hypes                                   int64
Hype points                             int64
Views                                   int64
Watch time (hours)                    float64
Subscribers                             int64
Impressions                             int64
Impressions click-through rate (%)    float64
dtype: object

In [160]:
df.index

Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60],
      dtype='int64')

In [161]:
type(df)

pandas.core.frame.DataFrame

In [162]:
type(df.index)

pandas.core.indexes.base.Index

In [163]:
type(df.columns)

pandas.core.indexes.base.Index

In [164]:
type(df["Views"])

pandas.core.series.Series

In [165]:
df["Views"]

1     1794814
2      489865
3       29662
4       29639
5       15884
6       28466
7       32516
8        1992
9       34387
10       1733
11       6893
12      24405
13       1806
14      22437
15       1802
16        918
17       1335
18       5925
19       1917
20       9832
21       2749
22       6114
23       1399
24       1714
25        286
26         94
27       1474
28        985
29       1731
30       4331
31       2941
32       2900
33       1805
34       2292
35       1070
36       7966
37       5522
38        142
39        881
40         91
41        135
42       1657
43        919
44        117
45       1185
46       1203
47       1871
48       2058
49       2092
50       1558
51       1666
52       1607
53         77
54       1347
55       2721
56       2255
57        231
58       2269
59       1264
60       1792
Name: Views, dtype: int64

In [166]:
df.iloc[0]

Content                                     VE6EZGr29NA
Video title                           Chikiri 👌 Lyrics💀
Video publish time                         Nov 11, 2025
Duration                                           16.0
Subscribers gained                                  562
Subscribers lost                                     82
Likes                                             15593
Dislikes                                            670
Likes (vs dislikes) (%)                           95.88
Shares                                              157
Comments added                                       69
Remix count                                        11.0
Remix views                                      6533.0
Engaged views                                    891614
Average view duration                           0:00:15
Average percentage viewed (%)                     98.03
Stayed to watch (%)                               67.24
Unique viewers                                      NaN
Unique reach                                          0
Average views per viewer                            NaN
New viewers                                         NaN
Returning viewers                                   NaN
Casual viewers                                      NaN
Regular viewers                                     NaN
Hypes                                                 0
Hype points                                           0
Views                                           1794814
Watch time (hours)                            4089.6655
Subscribers                                         480
Impressions                                       10891
Impressions click-through rate (%)                 6.88
Name: 1, dtype: object

In [167]:
df.reset_index(drop=True, inplace=True)

In [168]:
df.index

RangeIndex(start=0, stop=60, step=1)

In [169]:
df.head()

,Content,Video title,Video publish time,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average view duration,Average percentage viewed (%),Stayed to watch (%),Unique viewers,Unique reach,Average views per viewer,New viewers,Returning viewers,Casual viewers,Regular viewers,Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
0,VE6EZGr29NA,Chikiri 👌 Lyrics💀,"Nov 11, 2025",16.0,562,82,15593,670,95.88,157,69,11.0,6533.0,891614,0:00:15,98.03,67.24,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,1794814,4089.6655,480,10891,6.88
1,H6yMF28ZyQk,IBOMMA RAVI Case Solved!,"Nov 19, 2025",6.0,41,14,2365,82,96.65,13,15,NaN,NaN,155069,0:00:13,219.10,76.05,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,489865,589.3004,27,877,3.88
2,irfyNRSMh88,ME IN 2025,"Dec 3, 2025",12.0,10,0,141,6,95.92,5,0,NaN,NaN,14483,0:00:12,104.64,75.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29662,52.8250,10,476,3.57
3,NA2ZvoTvR6c,"If you can survive this, you can survive anyth...","Dec 22, 2025",8.0,6,0,236,3,98.74,83,5,NaN,NaN,13960,0:00:09,118.19,74.36,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,29639,39.1920,6,443,6.32
4,38KNroE0RcI,Daddy covering after hurting MOM 😅😂,"Dec 2, 2025",35.0,5,0,55,6,90.16,5,0,NaN,NaN,7420,0:00:24,70.31,57.63,NaN,0,NaN,NaN,NaN,NaN,NaN,0,0,15884,53.6322,5,554,1.08

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Content                             60 non-null     object
 1   Video title                         60 non-null     object
 2   Video publish time                  60 non-null     object
 3   Duration                            60 non-null     float64
 4   Subscribers gained                  60 non-null     int64
 5   Subscribers lost                    60 non-null     int64
 6   Likes                               60 non-null     int64
 7   Dislikes                            60 non-null     int64
 8   Likes (vs dislikes) (%)             60 non-null     float64
 9   Shares                              60 non-null     int64
 10  Comments added                      60 non-null     int64
 11  Remix count                         1 non-null      float64
 12  Remix views                         1 non-null      float64
 13  Engaged views                       60 non-null     int64
 14  Average view duration               60 non-null     object
 15  Average percentage viewed (%)       60 non-null     float64
 16  Stayed to watch (%)                 60 non-null     float64
 17  Unique viewers                      0 non-null      float64
 18  Unique reach                        60 non-null     int64
 19  Average views per viewer            0 non-null      float64
 20  New viewers                         0 non-null      float64
 21  Returning viewers                   0 non-null      float64
 22  Casual viewers                      0 non-null      float64
 23  Regular viewers                     0 non-null      float64
 24  Hypes                               60 non-null     int64
 25  Hype points                         60 non-null     int64
 26  Views                               60 non-null     int64
 27  Watch time (hours)                  60 non-null     float64
 28  Subscribers                         60 non-null     int64
 29  Impressions                         60 non-null     int64
 30  Impressions click-through rate (%)  60 non-null     float64
dtypes: float64(14), int64(13), object(4)
memory usage: 14.7+ KB

In [171]:
df.isnull()

,Content,Video title,Video publish time,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average view duration,Average percentage viewed (%),Stayed to watch (%),Unique viewers,Unique reach,Average views per viewer,New viewers,Returning viewers,Casual viewers,Regular viewers,Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
57,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,True,True,True,True,True,False,False,False,False,False,False,False

In [172]:
df.isnull().sum()

Content                                0
Video title                            0
Video publish time                     0
Duration                               0
Subscribers gained                     0
Subscribers lost                       0
Likes                                  0
Dislikes                               0
Likes (vs dislikes) (%)                0
Shares                                 0
Comments added                         0
Remix count                           59
Remix views                           59
Engaged views                          0
Average view duration                  0
Average percentage viewed (%)          0
Stayed to watch (%)                    0
Unique viewers                        60
Unique reach                           0
Average views per viewer              60
New viewers                           60
Returning viewers                     60
Casual viewers                        60
Regular viewers                       60
Hypes                                  0
Hype points                            0
Views                                  0
Watch time (hours)                     0
Subscribers                            0
Impressions                            0
Impressions click-through rate (%)     0
dtype: int64

In [173]:
df[["Unique reach", "Hypes", "Hype points"]].describe()

       Unique reach  Hypes  Hype points
count          60.0   60.0         60.0
mean            0.0    0.0          0.0
std             0.0    0.0          0.0
min             0.0    0.0          0.0
25%             0.0    0.0          0.0
50%             0.0    0.0          0.0
75%             0.0    0.0          0.0
max             0.0    0.0          0.0

In [174]:
df.describe()

,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average percentage viewed (%),Stayed to watch (%),Unique viewers,Unique reach,Average views per viewer,New viewers,Returning viewers,Casual viewers,Regular viewers,Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
count,60.000000,60.000000,60.000000,60.00000,60.000000,60.000000,60.000000,60.000000,1.0,1.0,60.000000,60.000000,60.000000,0.0,60.0,0.0,0.0,0.0,0.0,0.0,60.0,60.0,6.000000e+01,60.000000,60.000000,60.000000,60.000000
mean,10.566667,10.750000,1.666667,331.35000,13.416667,97.622833,6.250000,2.216667,11.0,6533.0,19777.733333,124.168000,56.262833,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.351232e+04,86.264160,9.083333,708.616667,5.198500
std,6.847904,72.577866,10.703503,2026.62845,86.846893,3.503365,23.119164,9.036820,NaN,NaN,116212.882486,46.080991,12.746556,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.384388e+05,531.120785,61.940729,1373.924493,4.303104
min,3.000000,0.000000,0.000000,4.00000,0.000000,86.360000,0.000000,0.000000,11.0,6533.0,25.000000,44.970000,30.930000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.700000e+01,0.054200,0.000000,55.000000,1.080000
25%,6.000000,0.000000,0.000000,10.75000,0.000000,96.092500,0.000000,0.000000,11.0,6533.0,384.500000,93.297500,45.695000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.248750e+03,1.145225,0.000000,333.500000,2.762500
50%,8.500000,0.000000,0.000000,18.50000,0.000000,100.000000,1.000000,0.000000,11.0,6533.0,648.500000,120.280000,55.870000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.805500e+03,2.044850,0.000000,503.000000,3.735000
75%,12.000000,1.000000,0.000000,38.00000,1.000000,100.000000,2.000000,2.000000,11.0,6533.0,2182.500000,144.735000,66.050000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5.622750e+03,6.923050,1.000000,781.500000,5.937500
max,35.000000,562.000000,82.000000,15593.00000,670.000000,100.000000,157.000000,69.000000,11.0,6533.0,891614.000000,306.840000,80.750000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.794814e+06,4089.665500,480.000000,10891.000000,23.610000

In [175]:
columns_to_drop = [
    "Unique viewers",
    "Average views per viewer",
    "Returning viewers",
    "New viewers",
    "Casual viewers",
    "Regular viewers",
    "Unique reach"
]

df = df.drop(columns=columns_to_drop)

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Content                             60 non-null     object
 1   Video title                         60 non-null     object
 2   Video publish time                  60 non-null     object
 3   Duration                            60 non-null     float64
 4   Subscribers gained                  60 non-null     int64
 5   Subscribers lost                    60 non-null     int64
 6   Likes                               60 non-null     int64
 7   Dislikes                            60 non-null     int64
 8   Likes (vs dislikes) (%)             60 non-null     float64
 9   Shares                              60 non-null     int64
 10  Comments added                      60 non-null     int64
 11  Remix count                         1 non-null      float64
 12  Remix views                         1 non-null      float64
 13  Engaged views                       60 non-null     int64
 14  Average view duration               60 non-null     object
 15  Average percentage viewed (%)       60 non-null     float64
 16  Stayed to watch (%)                 60 non-null     float64
 17  Hypes                               60 non-null     int64
 18  Hype points                         60 non-null     int64
 19  Views                               60 non-null     int64
 20  Watch time (hours)                  60 non-null     float64
 21  Subscribers                         60 non-null     int64
 22  Impressions                         60 non-null     int64
 23  Impressions click-through rate (%)  60 non-null     float64
dtypes: float64(8), int64(12), object(4)
memory usage: 11.4+ KB

In [177]:
df.shape

(60, 24)

In [179]:
df.describe()

,Duration,Subscribers gained,Subscribers lost,Likes,Dislikes,Likes (vs dislikes) (%),Shares,Comments added,Remix count,Remix views,Engaged views,Average percentage viewed (%),Stayed to watch (%),Hypes,Hype points,Views,Watch time (hours),Subscribers,Impressions,Impressions click-through rate (%)
count,60.000000,60.000000,60.000000,60.00000,60.000000,60.000000,60.000000,60.000000,1.0,1.0,60.000000,60.000000,60.000000,60.0,60.0,6.000000e+01,60.000000,60.000000,60.000000,60.000000
mean,10.566667,10.750000,1.666667,331.35000,13.416667,97.622833,6.250000,2.216667,11.0,6533.0,19777.733333,124.168000,56.262833,0.0,0.0,4.351232e+04,86.264160,9.083333,708.616667,5.198500
std,6.847904,72.577866,10.703503,2026.62845,86.846893,3.503365,23.119164,9.036820,NaN,NaN,116212.882486,46.080991,12.746556,0.0,0.0,2.384388e+05,531.120785,61.940729,1373.924493,4.303104
min,3.000000,0.000000,0.000000,4.00000,0.000000,86.360000,0.000000,0.000000,11.0,6533.0,25.000000,44.970000,30.930000,0.0,0.0,7.700000e+01,0.054200,0.000000,55.000000,1.080000
25%,6.000000,0.000000,0.000000,10.75000,0.000000,96.092500,0.000000,0.000000,11.0,6533.0,384.500000,93.297500,45.695000,0.0,0.0,1.248750e+03,1.145225,0.000000,333.500000,2.762500
50%,8.500000,0.000000,0.000000,18.50000,0.000000,100.000000,1.000000,0.000000,11.0,6533.0,648.500000,120.280000,55.870000,0.0,0.0,1.805500e+03,2.044850,0.000000,503.000000,3.735000
75%,12.000000,1.000000,0.000000,38.00000,1.000000,100.000000,2.000000,2.000000,11.0,6533.0,2182.500000,144.735000,66.050000,0.0,0.0,5.622750e+03,6.923050,1.000000,781.500000,5.937500
max,35.000000,562.000000,82.000000,15593.00000,670.000000,100.000000,157.000000,69.000000,11.0,6533.0,891614.000000,306.840000,80.750000,0.0,0.0,1.794814e+06,4089.665500,480.000000,10891.000000,23.610000

In [180]:
df.isnull().sum()

Content                                0
Video title                            0
Video publish time                     0
Duration                               0
Subscribers gained                     0
Subscribers lost                       0
Likes                                  0
Dislikes                               0
Likes (vs dislikes) (%)                0
Shares                                 0
Comments added                         0
Remix count                           59
Remix views                           59
Engaged views                          0
Average view duration                  0
Average percentage viewed (%)          0
Stayed to watch (%)                    0
Hypes                                  0
Hype points                            0
Views                                  0
Watch time (hours)                     0
Subscribers                            0
Impressions                            0
Impressions click-through rate (%)     0
dtype: int64

In [182]:
df.to_csv("../data/processed/youtube_shorts_cleaned.csv", index=False)